version: "3.9"

services:
  app:
    image: personal-site
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"